# Generated by Django 3.2.7 on 2021-10-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=13)),
                ('lastName', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, verbose_name='me@lms.org')),
                ('course_id', models.CharField(max_length=130, verbose_name='')),
                ('user_id', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
