# Generated by Django 3.2.7 on 2021-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.CharField(default='9fc08cd6-0481-488f-bb55-18d64db37a38', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(default='e562bf93-b51f-4ea7-a108-10ce1360608f', max_length=300),
        ),
    ]
