# Generated by Django 3.2.7 on 2021-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20211020_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.CharField(default='30bb8f52-1239-4df5-a36c-776a12123788', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.CharField(default='[4]', max_length=1300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(default='6fe3bb8e-5216-449a-aa1e-c2e5d118b406', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.CharField(default='[4]', max_length=1300),
        ),
    ]
