# Generated by Django 3.2.7 on 2021-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20211021_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.CharField(default='6af49226-cc6e-4c8a-95d7-af6aaf579c6c', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(default='f0b2909c-f56f-4e91-a8f0-6486c336686d', max_length=300),
        ),
    ]
