# Generated by Django 3.2.7 on 2021-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20211022_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.CharField(default='3c30f64e-c56c-4520-8042-6cd9bb38f599', max_length=300),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='public_id',
            field=models.CharField(default='ce03a35a-804b-4046-93d9-19cbac9bf41b', max_length=300),
        ),
    ]
