"""chages

Revision ID: 8fa6dc3ff16f
Revises: 
Create Date: 2020-09-12 22:13:07.265924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa6dc3ff16f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    op.drop_table('savings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=64), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('time', sa.FLOAT(), nullable=True),
    sa.CheckConstraint('confirmed IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('rate', sa.INTEGER(), nullable=True),
    sa.Column('interval', sa.VARCHAR(), nullable=True),
    sa.Column('stop', sa.VARCHAR(length=64), nullable=True),
    sa.Column('start', sa.VARCHAR(length=64), nullable=True),
    sa.Column('total_amount', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
