"""new tables

Revision ID: d1e299744cd9
Revises: 
Create Date: 2020-08-25 05:00:41.992998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e299744cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plans', sa.Column('interval', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('start', sa.String(length=64), nullable=True))
    op.add_column('plans', sa.Column('stop', sa.String(length=64), nullable=True))
    op.add_column('plans', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.drop_column('plans', 'total')
    op.add_column('users', sa.Column('account_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('account_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_nok', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('location_nok', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name_nok', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone_nok', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('plans', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('relationship', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('saved', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('withdrawn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'withdrawn')
    op.drop_column('users', 'state')
    op.drop_column('users', 'saved')
    op.drop_column('users', 'relationship')
    op.drop_column('users', 'plans')
    op.drop_column('users', 'phone_nok')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'name_nok')
    op.drop_column('users', 'location_nok')
    op.drop_column('users', 'email_nok')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'account_number')
    op.drop_column('users', 'account_name')
    op.add_column('plans', sa.Column('total', sa.INTEGER(), nullable=True))
    op.drop_column('plans', 'total_amount')
    op.drop_column('plans', 'stop')
    op.drop_column('plans', 'start')
    op.drop_column('plans', 'interval')
    op.drop_table('savings')
    # ### end Alembic commands ###
