# Generated by Django 3.2.7 on 2021-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='public_id',
            field=models.CharField(default='a181b7a4-9203-4874-92b7-597e9733f437', max_length=300),
        ),
    ]
