# Generated by Django 3.2.7 on 2021-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='public_id',
            field=models.CharField(default='609876e0-5bee-4c45-9a42-a5badd52dc44', max_length=300),
        ),
    ]
