# Generated by Django 3.2.7 on 2021-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='public_id',
            field=models.CharField(default='7608db47-edf4-4a57-87d9-9be4bcfb1e68', max_length=300),
        ),
    ]
